name: neverending-serve

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  APP_DOMAIN: barely-assured-whale.ngrok-free.app

concurrency:
  group: "neverending-serve"
  cancel-in-progress: true

jobs:
  serve:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create docker-compose.yaml
        run: |
          cat << EOF > docker-compose.yaml
          version: '3.8'
          services:
            web:
              build:
                context: .
                dockerfile_inline: |
                  FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim
                  WORKDIR /app
                  COPY app.py .
                  EXPOSE 8000
              ports:
                - "8000:8000"
              volumes:
                - .:/app
                - /app/.git
              environment:
                APP_DOMAIN: ${{ env.APP_DOMAIN }}
              command: uv run app.py
          EOF

      - name: Run server with docker-compose
        run: docker compose -f docker-compose.yaml up -d

      - name: Start Ngrok Tunnel
        uses: esc5221/ngrok-tunnel-action@v1.0.2
        with:
          timeout: 6h
          port: "8000 --domain=${{ env.APP_DOMAIN }}"
          ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
          tunnel_type: http
          save_url_to_filename: tunnel_url.md

      - name: Monitor Domain and Restart on Error
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
        run: |
          # monitor the domain and restart the workflow if an error is detected
          while true; do
            HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" https://${{ env.APP_DOMAIN }})
            if [ "$HTTP_STATUS" -ne 200 ]; then
              echo "Error detected with status code $HTTP_STATUS. Restarting workflow..."
              exit 1
            else
              echo "Domain is healthy with status code $HTTP_STATUS."
            fi
            sleep 60
          done &

      - name: Tail logs
        run: timeout 4h docker compose -f docker-compose.yaml logs -f

      - name: Dispatch next workflow run
        if: failure()
        uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: "neverending-serve.yaml"
